# Generated by Django 3.1.4 on 2021-01-31 12:58

from django.db import migrations, models
import excel_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('key', models.CharField(default=excel_api.models.gen_code, max_length=20, unique=True)),
                ('call_used_today', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_unlimited', models.BooleanField(default=False)),
                ('api_per_day', models.IntegerField()),
            ],
        ),
    ]
