# Generated by Django 3.0.7 on 2020-12-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('action_can_be_taken', models.ManyToManyField(to='bot.Action')),
            ],
        ),
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1024)),
                ('last_name', models.CharField(max_length=1024)),
                ('tg_id', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('current_action', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Action')),
                ('current_location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bot.Location')),
            ],
        ),
    ]
