# Generated by Django 3.0.7 on 2020-12-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20201219_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('GO', 'Go to Page'), ('AC', 'Perform action')], default='GO', max_length=2),
            preserve_default=False,
        ),
    ]
