# Generated by Django 3.0.7 on 2020-12-20 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20201220_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='current_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Action'),
        ),
    ]
