# Generated by Django 3.0.7 on 2020-12-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20201220_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='end_action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
