# Generated by Django 3.0.7 on 2020-12-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20201221_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_developing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tguser',
            name='alphavantage_api_key',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tguser',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
    ]
