# Generated by Django 3.1.4 on 2021-01-01 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_arkfund_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='subscribed_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriber', to='bot.arkfund'),
        ),
        migrations.RemoveField(
            model_name='arkfund',
            name='stocks',
        ),
        migrations.AddField(
            model_name='arkfund',
            name='stocks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund', to='bot.arkstock'),
        ),
        migrations.AlterField(
            model_name='arkstock',
            name='shares',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
