# Generated by Django 3.1.4 on 2021-01-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_auto_20210101_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkstock',
            name='shares_delta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arkstock',
            name='weight_delta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
