# Generated by Django 3.1.4 on 2021-01-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20210101_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arkfund',
            name='stocks',
        ),
        migrations.AddField(
            model_name='arkfund',
            name='stocks',
            field=models.ManyToManyField(null=True, related_name='fund', to='bot.ArkStock'),
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='subscribed_fund',
        ),
        migrations.AddField(
            model_name='tguser',
            name='subscribed_fund',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscriber', to='bot.ArkFund'),
        ),
    ]
