# Generated by Django 3.1.4 on 2021-01-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_auto_20210101_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='arkstock',
            name='shares_delta_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
