# Generated by Django 3.1.4 on 2021-01-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_arkstock_shares_delta_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkfund',
            name='stocks',
            field=models.ManyToManyField(blank=True, related_name='fund', to='bot.ArkStock'),
        ),
    ]
