# Generated by Django 3.1.4 on 2021-01-01 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_auto_20210101_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arkfund',
            name='stocks',
        ),
        migrations.AddField(
            model_name='arkstock',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='bot.arkfund'),
        ),
    ]
