# Generated by Django 3.1.4 on 2021-01-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_auto_20210101_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arkstock',
            name='weight_delta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
