# Generated by Django 3.1.4 on 2021-01-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_auto_20210101_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='custom_text',
            field=models.TextField(blank=True),
        ),
    ]
