# Generated by Django 3.1.4 on 2021-01-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_location_custom_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='custom_text',
        ),
    ]
