# Generated by Django 3.1.4 on 2021-01-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_remove_location_custom_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arkstock',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='subscribed_fund',
        ),
        migrations.DeleteModel(
            name='ArkFund',
        ),
        migrations.DeleteModel(
            name='ArkStock',
        ),
    ]
